### PR TITLE
Implement `purge_behavior` parameter

### PR DESCRIPTION
**Pull request by reidmv**
This allows for specifying classes or data keys that should be present or have defined values, without removing or modifying other data already present in the node group.

### CODE REVIEW

**Comment by reidmv** [comment]
@WhatsARanjit care to review?

**Comment by reidmv** [comment]
@WhatsARanjit does anyone else have merge access to this repo? If not, would you be open to designating a few people?

**Comment by WhatsARanjit** [comment]
@reidmv Sorry for being absent.  This is fine with me, but can you whip up some corresponding tests for purging in different scenarios?  Thanks.

**Comment by reidmv** [comment]
Sure, I'll take a stab at some basic tests. Will push an update when I have them.

**Comment by reidmv** [comment]
@WhatsARanjit a base set of tests implemented and pushed to PR. Waiting for Travis to complete; had to change the Gemfile to get a modern puppetlabs_spec_helper, waiting to see if it broke any of the other tests.

**Comment by reidmv** [comment]
@WhatsARanjit latest commit should fix the tests. I went through and updated the syntax of the small number of existing tests to use rspec mocks, rather than mocha, and unpinned some ancient gem versions. Tests should now pass.

**Comment by reidmv** [comment]
@WhatsARanjit thanks!! Do you think we could get a new module release with this feature? 🙂

**Comment by reidmv** [comment]
@WhatsARanjit ping

Btw, there's some neat Forge publish automation a colleague did a short bit ago that lets you auto-update the `metadata.json` file with a new version number, commit it, update the release tag, and push to the Forge all through a Github Action. [Details here](https://github.com/puppetlabs/dellemc-powerstore/blob/main/.github/workflows/release.yml). It makes releasing a new version as easy as [creating a new release in the Github UI](https://github.com/WhatsARanjit/puppet-node_manager/releases).

**Comment by WhatsARanjit** [comment]
Good to go!  Thanks @reidmv 

https://forge.puppet.com/modules/WhatsARanjit/node_manager/0.7.4

**Comment by reidmv** [comment]
W00t!!! Awesome, thanks @WhatsARanjit!! 😄

**Pull request merged**
